package com.elitecore.sm.roaming.model;

import javax.xml.bind.annotation.XmlEnumValue;

public enum TimeZoneEnum {

	@XmlEnumValue("AustralianCentralDaylightSavingsTime")AustralianCentralDaylightSavingsTime("UTC+10:30"),
	@XmlEnumValue("AustralianCentralStandardTime")AustralianCentralStandardTime("UTC+09:30"),
	@XmlEnumValue("AcreTime")AcreTime("UTC−05"),
	@XmlEnumValue("ASEANCommonTime")ASEANCommonTime("UTC+06:30 – UTC+09"),
	@XmlEnumValue("AustralianCentralWesternStandardTime")AustralianCentralWesternStandardTime("UTC+08:45"),
	@XmlEnumValue("AtlanticDaylightTime")AtlanticDaylightTime("UTC−03"),
	@XmlEnumValue("AustralianEasternDaylightSavingsTime")AustralianEasternDaylightSavingsTime("UTC+11"),
    @XmlEnumValue("AustralianEasternStandardTime")AustralianEasternStandardTime("UTC+10"),	
    @XmlEnumValue("AfghanistanTime")AfghanistanTime("UTC+04:30"),	
    @XmlEnumValue("AlaskaDaylightTime")AlaskaDaylightTime("UTC−08"),
    @XmlEnumValue("AlaskaStandardTime")AlaskaStandardTime("UTC−09"),
    @XmlEnumValue("AmazonSummerTime")AmazonSummerTime("UTC−03"),
    @XmlEnumValue("AmazonTime")AmazonTime("UTC−04"),
    @XmlEnumValue("ArmeniaTime")ArmeniaTime("UTC+04b"),
    @XmlEnumValue("ArgentinaTime")ArgentinaTime("UTC−03"),
    @XmlEnumValue("ArabiaStandardTime")ArabiaStandardTime("UTC+03"),
    @XmlEnumValue("AtlanticStandardTime")AtlanticStandardTime("UTC−04"), 
    @XmlEnumValue("AustralianWesternStandardTime")AustralianWesternStandardTime("UTC+08"), 	
    @XmlEnumValue("AzoresSummerTime")AzoresSummerTime("UTC±00"), 	
    @XmlEnumValue("AzoresStandardTime")AzoresStandardTime("UTC−01"), 	
    @XmlEnumValue("AzerbaijanTime")AzerbaijanTime("UTC+04"), 	
    @XmlEnumValue("BruneiTime")BruneiTime("UTC+08"), 	
    @XmlEnumValue("BritishIndianOceanTime")BritishIndianOceanTime("UTC+06"),
    @XmlEnumValue("BakerIslandTime")BakerIslandTime("UTC−12"),
    @XmlEnumValue("BoliviaTime")BoliviaTime("UTC−04"),
    @XmlEnumValue("BrasíliaSummerTime")BrasíliaSummerTime("UTC−02"),
    @XmlEnumValue("BrasiliaTime")BrasiliaTime("UTC−03"),
    @XmlEnumValue("BangladeshStandardTime")BangladeshStandardTime("UTC+06"),
    @XmlEnumValue("BougainvilleStandardTime")BougainvilleStandardTime("UTC+11"),
    @XmlEnumValue("BritishSummerTime")BritishSummerTime("UTC+01"),
    @XmlEnumValue("BhutanTime")BhutanTime("UTC+06"),
    @XmlEnumValue("CocosIslandsTime")CocosIslandsTime("UTC+06:30"),
    @XmlEnumValue("CentralDaylightTime")CentralDaylightTime("UTC−05"),
    @XmlEnumValue("CubaDaylightTime")CubaDaylightTime("UTC−04"),
    @XmlEnumValue("CentralEuropeanSummerTime")CentralEuropeanSummerTime("UTC+02"),
    @XmlEnumValue("CentralEuropeanTime")CentralEuropeanTime("UTC+01"),
    @XmlEnumValue("ChathamDaylightTime")ChathamDaylightTime("UTC+13:45"),
    @XmlEnumValue("ChathamStandardTime")ChathamStandardTime("UTC+12:45"),
    @XmlEnumValue("ChoibalsanStandardTime")ChoibalsanStandardTime("UTC+08"),
    @XmlEnumValue("ChoibalsanSummerTime")ChoibalsanSummerTime("UTC+09"),
    @XmlEnumValue("ChamorroStandardTime")ChamorroStandardTime("UTC+10"),
    @XmlEnumValue("ChuukTime")ChuukTime("UTC+10"),
    @XmlEnumValue("ClippertonIslandStandardTime")ClippertonIslandStandardTime("UTC−08"),
    @XmlEnumValue("CentralIndonesiaTime")CentralIndonesiaTime("UTC+08"),
    @XmlEnumValue("CookIslandTime")CookIslandTime("UTC−10"),
    @XmlEnumValue("ChileSummerTime")ChileSummerTime("UTC−03"),
    @XmlEnumValue("ChileStandardTime")ChileStandardTime("UTC−04"),
    @XmlEnumValue("ColombiaSummerTime")ColombiaSummerTime("UTC−04"),
    @XmlEnumValue("ColombiaTime")ColombiaTime("UTC−05"),
    @XmlEnumValue("CentralStandardTime")CentralStandardTime("UTC−06"),
    @XmlEnumValue("ChinaStandardTime")ChinaStandardTime("UTC+08"),
    @XmlEnumValue("AustralianCentralDaylightTime")AustralianCentralDaylightTime("UTC+10:30"),
    @XmlEnumValue("CubaStandardTime")CubaStandardTime("UTC−05"),
    @XmlEnumValue("Chinatime")Chinatime("UTC+08"),
    @XmlEnumValue("CapeVerdeTime")CapeVerdeTime("UTC−01"),
    @XmlEnumValue("CentralWesternStandardTime")CentralWesternStandardTime("UTC+08:45"),
    @XmlEnumValue("ChristmasIslandTime")ChristmasIslandTime("UTC+07"),
    @XmlEnumValue("DavisTime")DavisTime("UTC+07"),
    @XmlEnumValue("Dumontd'UrvilleTime")DumontdUrvilleTime("UTC+10"),
    @XmlEnumValue("AIX-specificequivalentofCentralEuropeanTime")AIXspecificequivalentofCentralEuropeanTime("UTC+01"),
    @XmlEnumValue("EasterIslandSummerTime")EasterIslandSummerTime("UTC−05"),
    @XmlEnumValue("EasterIslandStandardTime")EasterIslandStandardTime("UTC−06"),
    @XmlEnumValue("EastAfricaTime")EastAfricaTime("UTC−03"),
    @XmlEnumValue("EasternCaribbeanime")EasternCaribbeanime("UTC−04"),
    @XmlEnumValue("EcuadorTime")EcuadorTime("UTC−05"),
    @XmlEnumValue("EasternDaylightTime")EasternDaylightTime("UTC−04"),
    @XmlEnumValue("AustralianEasternSummerTime")AustralianEasternSummerTime("UTC+11"),
    @XmlEnumValue("EasternEuropeanSummerTime")EasternEuropeanSummerTime("UTC+03"),
    @XmlEnumValue("EasternEuropeanTime")EasternEuropeanTime("UTC+02"),
    @XmlEnumValue("EasternGreenlandSummerTime")EasternGreenlandSummerTime("UTC±00"),
    @XmlEnumValue("EasternGreenlandTime")EasternGreenlandTime("UTC−01"),
    @XmlEnumValue("EasternIndonesianTime")EasternIndonesianTime("UTC+09"),
    @XmlEnumValue("EasternStandardTime")EasternStandardTime("UTC−05"),
    @XmlEnumValue("FurthereasternEuropeanTime")FurthereasternEuropeanTime("UTC−03"),
    @XmlEnumValue("FijiTime")FijiTime("UTC+12"),
    @XmlEnumValue("FalklandIslandsSummerTime")FalklandIslandsSummerTime("UTC−03"),
    @XmlEnumValue("FalklandIslandsTime")FalklandIslandsTime("UTC−04"),
    @XmlEnumValue("FernandodeNoronhaTime")FernandodeNoronhaTime("UTC−02"),
    @XmlEnumValue("GalapagosTime")GalapagosTime("UTC−06"),
    @XmlEnumValue("GambierIslandsTime")GambierIslandsTime("UTC−09"),
    @XmlEnumValue("GeorgiaStandardTime")GeorgiaStandardTime("UTC+04"),
    @XmlEnumValue("FrenchGuianaTime")FrenchGuianaTime("UTC−03"),
    @XmlEnumValue("GilbertIslandTime")GilbertIslandTime("UTC+12"),
    @XmlEnumValue("GambierIslandTime")GambierIslandTime("UTC−09"),
    @XmlEnumValue("GreenwichMeanTime")GreenwichMeanTime("UTC±00"),
    @XmlEnumValue("SouthGeorgiaandtheSouthSandwichIslandsTime")SouthGeorgiaandtheSouthSandwichIslandsTime("UTC−02"),
    @XmlEnumValue("GulfStandardTime")GulfStandardTime("UTC+04"),
    @XmlEnumValue("GuyanaTime")GuyanaTime("UTC−04"),
    @XmlEnumValue("HawaiiAleutianDaylightTime")HawaiiAleutianDaylightTime("UTC−09"),
    @XmlEnumValue("HeureAvanced'EuropeCentrale")HeureAvancedEuropeCentrale ("UTC+02"),
    @XmlEnumValue("HawaiiAleutianStandardTime")HawaiiAleutianStandardTime ("UTC−10"),
    @XmlEnumValue("HongKongTime")HongKongTime ("UTC+08"),
    @XmlEnumValue("HeardandMcDonaldIslandsTime")HeardandMcDonaldIslandsTime ("UTC+05"),
    @XmlEnumValue("KhovdSummerTime")KhovdSummerTime ("UTC+08"),
    @XmlEnumValue("KhovdStandardTime")KhovdStandardTime ("UTC+07"),
	@XmlEnumValue("Indochina Time")IndochinaTime("UTC+07"),
	
	
	
@XmlEnumValue("Israel Daylight Time")IsraelDaylightTime("UTC+03"),
	@XmlEnumValue("Indian Ocean Time")IndianOceanTime("UTC+03"),
	@XmlEnumValue("Iran Daylight Time")IranDaylightTime("UTC+04:30"),
@XmlEnumValue("Irkutsk Time")IrkutskTime("UTC+08"),
@XmlEnumValue("Iran Standard Time")IranStandardTime("UTC+03:30"),
@XmlEnumValue("Indian Standard Time")IndianStandardTime("UTC+05:30"), 
@XmlEnumValue("Irish Standard Time[6]")IrishStandardTime("UTC+01"),
@XmlEnumValue("Japan Standard Time")JapanStandardTime("UTC+09"),
@XmlEnumValue("Kyrgyzstan Time")KyrgyzstanTime("UTC+06"),
@XmlEnumValue("Kosrae Time")KosraeTime("UTC+11"),
@XmlEnumValue("Krasnoyarsk Time")KrasnoyarskTime("UTC+07"),
@XmlEnumValue("Korea Standard Time")KoreaStandardTime("UTC+09"),
@XmlEnumValue("Lord Howe Standard Time")LordHoweStandardTime("UTC+10:30"),
@XmlEnumValue("Lord Howe Summer Time")LordHoweSummerTime("UTC+11"),
@XmlEnumValue("Line Islands Time")LineIslandsTime("UTC+14"),
@XmlEnumValue("Magadan Time")MagadanTime("UTC+12"),
@XmlEnumValue("Marquesas Islands Time")MarquesasIslandsTime("UTC-09:30"),
@XmlEnumValue("Mawson Station Time")MawsonStationTime("UTC+05"),
@XmlEnumValue("Mountain Daylight Time (North America)")MountainDaylightTime_NorthAmerica("UTC-06"),
@XmlEnumValue("Middle European Time Same zone as CET")MiddleEuropeanTimeSamezoneasCET("UTC+01"),
@XmlEnumValue("Middle European Summer Time Same zone as CEST")MiddleEuropeanSummerTimeSamezoneasCEST("UTC+02"),
@XmlEnumValue("Marshall Islands Time")MarshallIslandsTime("UTC+12"),
@XmlEnumValue("Macquarie Island Station Time")MacquarieIslandStationTime("UTC+11"),
@XmlEnumValue("Myanmar Standard Time")Myanmar_Standard_Time("UTC-09:30"),
@XmlEnumValue("Moscow Time")MoscowTime("UTC+03"),
@XmlEnumValue("Malaysia Standard Time")MalaysiaStandardTime("UTC+08"),	
@XmlEnumValue("Mountain Standard Time (North America)")MountainStandardTime_NorthAmerica("UTC-07"),
@XmlEnumValue("Mauritius Time")MauritiusTime("UTC+04"),
@XmlEnumValue("Maldives Time")MaldivesTime("UTC+05"),
@XmlEnumValue("Malaysia Time")MalaysiaTime("UTC+08"),
@XmlEnumValue("New Caledonia Time")NewCaledoniaTime("UTC+11"),
@XmlEnumValue("Newfoundland Daylight Time")NewfoundlandDaylightTime("UTC-20:30"),
@XmlEnumValue("Norfolk Island Time")NorfolkIslandTime("UTC+11"),
@XmlEnumValue("Nepal Time")NepalTime("UTC+05:45"),
@XmlEnumValue("Newfoundland Standard Time")NewfoundlandStandardTime("UTC-03:30"),
@XmlEnumValue("Newfoundland Time")NewfoundlandTime("UTC-03:30"),
@XmlEnumValue("Niue Time")NiueTime("UTC-11"),
@XmlEnumValue("New Zealand Daylight Time")NewZealandDaylightTime("UTC+13"),
@XmlEnumValue("New Zealand Standard Time")NewZealandStandardTime("UTC+12"),
@XmlEnumValue("Omsk Time")OmskTime("UTC+06"),
@XmlEnumValue("Oral Time")OralTime("UTC+05"),
@XmlEnumValue("Pacific Daylight Time (North America)")PacificDaylightTimeNorthAmerica("UTC-07"),
@XmlEnumValue("Peru Time")PeruTime("UTC-05"),
@XmlEnumValue("Kamchatka Time")KamchatkaTime("UTC+12"),
@XmlEnumValue("Papua New Guinea Time")PapuaNewGuineaTime("UTC+10"),
@XmlEnumValue("Phoenix Island Time")PhoenixIslandTime("UTC+13"),
@XmlEnumValue("Philippine Time")PhilippineTime("UTC+08"),
@XmlEnumValue("Pakistan Standard Time")PakistanStandardTime("UTC+05"),
@XmlEnumValue("Saint Pierre and Miquelon Daylight Time")SaintPierreandMiquelonDaylightTime("UTC-02"),
@XmlEnumValue("Saint Pierre and Miquelon Standard Time")SaintPierreandMiquelonStandardTime("UTC-02"),
@XmlEnumValue("Pohnpei Standard Time")PohnpeiStandardTime("UTC+11"),
@XmlEnumValue("Pacific Standard Time (North America)")PacificStandardTimeNorthAmerica("UTC-08"),
@XmlEnumValue("Philippine Standard Time")PhilippineStandardTime("UTC+08"),
@XmlEnumValue("Paraguay Summer Time[7]")ParaguaySummerTime7("UTC-03"),	
@XmlEnumValue("Paraguay Time[8]")ParaguayTime8("UTC-04"),	
@XmlEnumValue("Reunion Time")ReunionTime("UTC+04"),
@XmlEnumValue("Rothera Research Station Time")RotheraResearchStationTime("UTC-03"),
@XmlEnumValue("Sakhalin Island Time")SakhalinIslandTime("UTC+11"),
@XmlEnumValue("Samara Time")SamaraTime("UTC+04"),
@XmlEnumValue("South African Standard Time")SouthAfricanStandardTime("UTC+02"),

@XmlEnumValue("Solomon Islands Time")SolomonIslandsTime("UTC+11"),
@XmlEnumValue("Seychelles Time")SeychellesTime("UTC+04"),
@XmlEnumValue("Samoa Daylight Time")SamoaDaylightTime("UTC-10"),
@XmlEnumValue("Singapore Time")SingaporeTime("UTC+08"),
@XmlEnumValue("Sri Lanka Standard Time")SriLankaStandardTime("UTC+05:30"),
@XmlEnumValue("Srednekolymsk Time")SrednekolymskTime("UTC+11"),
@XmlEnumValue("Suriname Time")SurinameTime("UTC-03"),
@XmlEnumValue("Samoa Standard Time")SamoaStandardTime("UTC-11"),
@XmlEnumValue("Singapore Standard Time")SingaporeStandardTime("UTC+08"),
@XmlEnumValue("Showa Station Time")ShowaStationTime("UTC+03"),
@XmlEnumValue("Tahiti Time")TahitiTime("UTC-10"),
@XmlEnumValue("Thailand Standard Time")ThailandStandardTime("UTC+07"),
@XmlEnumValue("Indian/Kerguelen")Indian_Kerguelen("UTC+05"),
@XmlEnumValue("Tajikistan Time")TajikistanTime("UTC+05"),
@XmlEnumValue("Tokelau Time")TokelauTime("UTC+13"),
@XmlEnumValue("Timor Leste Time")TimorLesteTime("UTC+09"),
@XmlEnumValue("Turkmenistan Time")TurkmenistanTime("UTC+05"),
@XmlEnumValue("Turkey Time")TurkeyTime("UTC+03"),
@XmlEnumValue("Tonga Time")TongaTime("UTC+13"),
@XmlEnumValue("Tuvalu Time")TuvaluTime("UTC+12"),
@XmlEnumValue("Ulaanbaatar Summer Time")UlaanbaatarSummerTime("UTC+09"),
@XmlEnumValue("Ulaanbaatar Standard Time")UlaanbaatarStandardTime("UTC+08"),
@XmlEnumValue("Kaliningrad Time")KaliningradTime("UTC+02"),
@XmlEnumValue("Coordinated Universal Time")CoordinatedUniversalTime("UTC+-00"),
@XmlEnumValue("Uruguay Summer Time")UruguaySummerTime("UTC-02"),
@XmlEnumValue("Uruguay Standard Time")UruguayStandardTime("UTC-03"),
@XmlEnumValue("Uzbekistan Time")UzbekistanTime("UTC+05"),
@XmlEnumValue("Venezuelan Standard Time")VenezuelanStandardTime("UTC-04"),
@XmlEnumValue("Vladivostok Time")VladivostokTime("UTC+10"),
@XmlEnumValue("Volgograd Time")VolgogradTime("UTC+04"),
@XmlEnumValue("Vostok Station Time")VostokStationTime("UTC+06"),
@XmlEnumValue("Vanuatu Time")VanuatuTime("UTC+11"),
@XmlEnumValue("Wake Island Time")WakeIslandTime("UTC+12"),
@XmlEnumValue("West Africa Summer Time")WestAfricaSummerTime("UTC+02"),
@XmlEnumValue("West Africa Time")WestAfricaTime("UTC+01"),
@XmlEnumValue("Western European Summer Time")WesternEuropeanSummerTime("UTC+01"),
@XmlEnumValue("Western European Time")WesternEuropeanTime("UTC+-00"),
@XmlEnumValue("Western Indonesian Time")WesternIndonesianTime("UTC+07"),
@XmlEnumValue("Western Standard Time")WesternStandardTime("UTC+08"),
@XmlEnumValue("Yakutsk Time")YakutskTime("UTC+09"),
@XmlEnumValue("Yekaterinburg Time")YekaterinburgTime("UTC+05");

	

	private String name;
	
	private TimeZoneEnum(String name) {
		this.name = name;
	}

	public String getTimeZoneEnum() {
		return this.name;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}
}
