package com.elitecore.sm.snmp.model;

public enum SNMPAlertTypeEnum {
	
	SERVER_INSTANCE,
	COLLECTION_SERVICE,
	DATA_CONSOLIDATION_SERVICE,
	DISTRIBUTION_SERVICE,
	GTPPRIME_COLLECTION_SERVICE,
	IPLOG_PARSING_SERVICE,
	NATFLOWBINARY_COLLECTION_SERVICE,
	NATFLOW_COLLECTION_SERVICE,
	PARSING_SERVICE,
	PROCESSING_SERVICE,
	RADIUS_COLLECTION_SERVICE,
	SYSLOG_COLLECTION_SERVICE,
	GENERIC,
	AGGREGATION_SERVICE,
	DIAMETER_COLLECTION_SERVICE,
	MQTT_COLLECTION_SERVICE,
	COAP_COLLECTION_SERVICE,
	HTTP2_COLLECTION_SERVICE	
	

}
