DECLARE 
 totalCount number(10);
BEGIN
  totalCount :=0;
FOR r1 IN (SELECT DISTINCT(LICENSEID) FROM TBLTPROFILENTITY where LICENSEID is not null) 
 LOOP 
  BEGIN
    FOR r2 IN (select DISTINCT(ENTITYALIAS) from TBLTPROFILENTITY WHERE ENTITYALIAS in ('VARIABLE_LENGTH_ASCII_PARSING_PLUGIN', 'VARIABLE_LENGTH_BINARY_PARSING_PLUGIN', 'PDF_PARSING_PLUGIN','XLS_PARSING_PLUGIN', 'HTML_PARSING_PLUGIN')) LOOP
      Select count(*) into totalCount from TBLTPROFILENTITY where ENTITYALIAS = r2.ENTITYALIAS and LICENSEID=r1.LICENSEID;
      IF (totalCount = 0)  THEN
        INSERT INTO TBLTPROFILENTITY( ID, CREATEDBYSTAFFID, CREATEDDATE,LASTUPDATEDBYSTAFFID, LASTUPDATEDDATE,STATUS, ENTITYALIAS, ENTITYTYPE,ISDEFAULT,SERVERTYPEID,LICENSEID)
        VALUES ((select max(id+1) from TBLTPROFILENTITY), 0,SYSDATE, 0, SYSDATE,'INACTIVE',r2.ENTITYALIAS,'PLUGIN_TYPE','N',1,
            r1.LICENSEID);
        INSERT INTO TBLTPROFILENTITY( ID, CREATEDBYSTAFFID, CREATEDDATE,LASTUPDATEDBYSTAFFID, LASTUPDATEDDATE,STATUS, ENTITYALIAS, ENTITYTYPE,ISDEFAULT,SERVERTYPEID,LICENSEID)
        VALUES ((select max(id+1) from TBLTPROFILENTITY), 0,SYSDATE, 0, SYSDATE,'INACTIVE',r2.ENTITYALIAS,'PLUGIN_TYPE','N',2,
            r1.LICENSEID);
        INSERT INTO TBLTPROFILENTITY( ID, CREATEDBYSTAFFID, CREATEDDATE,LASTUPDATEDBYSTAFFID, LASTUPDATEDDATE,STATUS, ENTITYALIAS, ENTITYTYPE,ISDEFAULT,SERVERTYPEID,LICENSEID)
        VALUES ((select max(id+1) from TBLTPROFILENTITY), 0,SYSDATE, 0, SYSDATE,'INACTIVE',r2.ENTITYALIAS,'PLUGIN_TYPE','N',3,
            r1.LICENSEID);
      END IF;
    END LOOP;
  END;
 END LOOP;
END;