package com.elitecore.sm.parser.model;

public enum PluginTypeEnum {
	ASCII_PARSING_PLUGIN,
	ASN1_PARSING_PLUGIN,
	DETAIL_LOCAL_PARSING_PLUGIN,
	DIGITEL_BINARY_PARSING_PLUGIN,
	FIXED_LENGTH_ASCII_PARSING_PLUGIN,
	MT_ALCATEL_BINARY_PARSING_PLUGIN,
	MT_SIEMENS_BINARY_PARSING_PLUGIN,
	NATFLOW_PARSING_PLUGIN,
	REGEX_PARSING_PLUGIN,
	XML_PARSING_PLUGIN,
	JSON_PARSING_PLUGIN,
	MTSIEMENS_BINARY_PARSING_PLUGIN
}
