package com.elitecore.sm.parser.model;

import javax.xml.bind.annotation.XmlEnumValue;


public enum UnifiedFieldEnum {
	
		@XmlEnumValue("APartyLocationCode")APartyLocationCode("APartyLocationCode"),
		@XmlEnumValue("APartyMDN")APartyMDN("APartyMDN"),
		@XmlEnumValue("APartyMIN")APartyMIN("APartyMIN"),
		@XmlEnumValue("BPartyLocationCode")BPartyLocationCode("BPartyLocationCode"),
		@XmlEnumValue("BPartyMDN")BPartyMDN("BPartyMDN"),
		@XmlEnumValue("BPartyMIN")BPartyMIN("BPartyMIN"),
		@XmlEnumValue("CPartyLocationCode")CPartyLocationCode("CPartyLocationCode"),		
		@XmlEnumValue("CPartyMDN")CPartyMDN("CPartyMDN"),
		@XmlEnumValue("CPartyMIN")CPartyMIN("CPartyMIN"),
		@XmlEnumValue("CallDirection")CallDirection("CallDirection"),
		@XmlEnumValue("DistanceBand")DistanceBand("DistanceBand"),
		@XmlEnumValue("Duration")Duration("Duration"),
		@XmlEnumValue("EgressCallDirection")EgressCallDirection("EgressCallDirection"),
		@XmlEnumValue("EgressEndDate")EgressEndDate("EgressEndDate"),
		@XmlEnumValue("EgressStartDate")EgressStartDate("EgressStartDate"),
		@XmlEnumValue("EgressTrunkGroupName")EgressTrunkGroupName("EgressTrunkGroupName"),
		@XmlEnumValue("EndDate")EndDate("EndDate"),
		@XmlEnumValue("EventSubType")EventSubType("EventSubType"),
		@XmlEnumValue("EventType")EventType("EventType"),
		@XmlEnumValue("General1")General1("General1"),
		@XmlEnumValue("General10")General10("General10"),
		@XmlEnumValue("General11")General11("General11"),
		@XmlEnumValue("General12")General12("General12"),
		@XmlEnumValue("General13")General13("General13"),
		@XmlEnumValue("General14")General14("General14"),
		@XmlEnumValue("General15")General15("General15"),
		@XmlEnumValue("General16")General16("General16"),
		@XmlEnumValue("General17")General17("General17"),
		@XmlEnumValue("General18")General18("General18"),
		@XmlEnumValue("General19")General19("General19"),
		@XmlEnumValue("General2")General2("General2"),
		@XmlEnumValue("General20")General20("General20"),
		@XmlEnumValue("General21")General21("General21"),
		@XmlEnumValue("General22")General22("General22"),
		@XmlEnumValue("General23")General23("General23"),
		@XmlEnumValue("General24")General24("General24"),
		@XmlEnumValue("General25")General25("General25"),
		@XmlEnumValue("General26")General26("General26"),
		@XmlEnumValue("General27")General27("General27"),
		@XmlEnumValue("General28")General28("General28"),
		@XmlEnumValue("General29")General29("General29"),
		@XmlEnumValue("General3")General3("General3"),
		@XmlEnumValue("General30")General30("General30"),
		@XmlEnumValue("General31")General31("General31"),
		@XmlEnumValue("General32")General32("General32"),
		@XmlEnumValue("General33")General33("General33"),
		@XmlEnumValue("General34")General34("General34"),
		@XmlEnumValue("General35")General35("General35"),
		@XmlEnumValue("General36")General36("General36"),
		@XmlEnumValue("General37")General37("General37"),
		@XmlEnumValue("General38")General38("General38"),
		@XmlEnumValue("General39")General39("General39"),
		@XmlEnumValue("General4")General4("General4"),
		@XmlEnumValue("General40")General40("General40"),
		@XmlEnumValue("General41")General41("General41"),
		@XmlEnumValue("General42")General42("General42"),
		@XmlEnumValue("General43")General43("General43"),
		@XmlEnumValue("General44")General44("General44"),
		@XmlEnumValue("General45")General45("General45"),
		@XmlEnumValue("General46")General46("General46"),
		@XmlEnumValue("General47")General47("General47"),
		@XmlEnumValue("General48")General48("General48"),
		@XmlEnumValue("General49")General49("General49"),
		@XmlEnumValue("General5")General5("General5"),
		@XmlEnumValue("General50")General50("General50"),
		@XmlEnumValue("General51")General51("General51"),
		@XmlEnumValue("General52")General52("General52"),
		@XmlEnumValue("General53")General53("General53"),
		@XmlEnumValue("General54")General54("General54"),
		@XmlEnumValue("General55")General55("General55"),
		@XmlEnumValue("General56")General56("General56"),
		@XmlEnumValue("General57")General57("General57"),
		@XmlEnumValue("General58")General58("General58"),
		@XmlEnumValue("General59")General59("General59"),
		@XmlEnumValue("General6")General6("General6"),
		@XmlEnumValue("General60")General60("General60"),
		@XmlEnumValue("General61")General61("General61"),
		@XmlEnumValue("General62")General62("General62"),
		@XmlEnumValue("General63")General63("General63"),
		@XmlEnumValue("General64")General64("General64"),
		@XmlEnumValue("General65")General65("General65"),
		@XmlEnumValue("General66")General66("General66"),
		@XmlEnumValue("General67")General67("General67"),
		@XmlEnumValue("General68")General68("General68"),
		@XmlEnumValue("General69")General69("General69"),
		@XmlEnumValue("General7")General7("General7"),
		@XmlEnumValue("General70")General70("General70"),
		@XmlEnumValue("General71")	General71("General71"),
		@XmlEnumValue("General72")General72("General72"),
		@XmlEnumValue("General73")General73("General73"),
		@XmlEnumValue("General74")General74("General74"),
		@XmlEnumValue("General75")General75("General75"),
		@XmlEnumValue("General76")General76("General76"),
		@XmlEnumValue("General77")	General77("General77"),
		@XmlEnumValue("General78")	General78("General78"),
		@XmlEnumValue("General79")	General79("General79"),
		@XmlEnumValue("General8")General8("General8"),
		@XmlEnumValue("General80")General80("General80"),
		@XmlEnumValue("General81")General81("General81"),
		@XmlEnumValue("General82")General82("General82"),
		@XmlEnumValue("General83")General83("General83"),
		@XmlEnumValue("General84")General84("General84"),
		@XmlEnumValue("General85")General85("General85"),
		@XmlEnumValue("General86")General86("General86"),
		@XmlEnumValue("General87")General87("General87"),
		@XmlEnumValue("General88")General88("General88"),
		@XmlEnumValue("General89")General89("General89"),
		@XmlEnumValue("General9")General9("General9"),
		@XmlEnumValue("General90")General90("General90"),
		@XmlEnumValue("General91")General91("General91"),
		@XmlEnumValue("General92")General92("General92"),
		@XmlEnumValue("General93")General93("General93"),
		@XmlEnumValue("General94")General94("General94"),
		@XmlEnumValue("General95")General95("General95"),
		@XmlEnumValue("General96")General96("General96"),
		@XmlEnumValue("General97")General97("General97"),
		@XmlEnumValue("General98")General98("General98"),
		@XmlEnumValue("General99")General99("General99"),
		@XmlEnumValue("General100")General100("General100"),
		
		@XmlEnumValue("IngressCallDirection")IngressCallDirection("IngressCallDirection"),
		@XmlEnumValue("IngressEndDate")IngressEndDate("IngressEndDate"),
		@XmlEnumValue("IngressStartDate")IngressStartDate("IngressStartDate"),
		@XmlEnumValue("IngressTrunkGroupName")IngressTrunkGroupName("IngressTrunkGroupName"),
		@XmlEnumValue("OnNetCode")OnNetCode("OnNetCode"),
		@XmlEnumValue("OriginalRecordNumber")	OriginalRecordNumber("OriginalRecordNumber"),
		@XmlEnumValue("PartnerId1")PartnerId1("PartnerId1"),
		@XmlEnumValue("PartnerId2")PartnerId2("PartnerId2"),
		@XmlEnumValue("RatingStream")RatingStream("RatingStream"),
		@XmlEnumValue("RecordNumber")RecordNumber("RecordNumber"),
		@XmlEnumValue("SourceUnitName")SourceUnitName("SourceUnitName"),
		@XmlEnumValue("StartDate")StartDate("StartDate"),
		@XmlEnumValue("SerialNumber")SerialNumber("SerialNumber");
		private String name;

		private UnifiedFieldEnum(String name) {
			this.name = name;
		}

		public String getUnifiedFiedEnum() {
			return this.name;
		}

		/**
		 * @return the name
		 */
		public String getName() {
			return name;
		}
		

}
