//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.04 at 02:29:40 PM IST 
//


package com.elitecore.sm.migration.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import org.dozer.Mapping;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startupMode",
    "mySortingType",
    "sortingCriteria",
    "executionInterval",
    "thirdPartyTransfer",
    "immediateExecuteOnStartup",
    "minimumThread",
    "maximumThread",
    "threadQueueSize",
    "fileBatchSize",
    "timestenDatasourceName",
    "processRecordLimit",
    "writeRecordLimit",
    "fileMerge",
    "driverList",
    "scheduling",
    "fileGrouping",
    "storeCdrFileSummaryInDb"
})
@XmlRootElement(name = "distribution-service")
public class DistributionServiceEntity {

    @XmlElement(name = "startup-mode", required = true)
    protected String startupMode;
    
    @XmlElement(name = "sorting-type", required = true)
    protected String mySortingType;
    
    @XmlElement(name = "sorting-criteria", required = true)
    protected String sortingCriteria;
    
    
    @XmlElement(name = "execution-interval")
    @Mapping("svcExecParams.executionInterval")
    protected byte executionInterval;
    
    @XmlElement(name = "third-party-transfer", required = true)
    @Mapping("thirdPartyTransferEnabled")
    protected String thirdPartyTransfer;
    
    @XmlElement(name = "immediate-execute-on-startup", required = true)
    @Mapping("svcExecParams.executeOnStartup")
    protected String immediateExecuteOnStartup;
    
    @XmlElement(name = "minimum-thread")
    @Mapping("svcExecParams.minThread")
    protected byte minimumThread;
    
    @XmlElement(name = "maximum-thread")
    @Mapping("svcExecParams.maxThread")
    protected byte maximumThread;
    
    @XmlElement(name = "thread-queue-size")
    @Mapping("svcExecParams.queueSize")
    protected short threadQueueSize;
    
    @XmlElement(name = "file-batch-size")
    @Mapping("svcExecParams.fileBatchSize")
    protected byte fileBatchSize;
    
    @XmlElement(name = "timesten-datasource-name", required = true)
    @Mapping("timestenDatasourceName")    
    protected String timestenDatasourceName;
    
    @XmlElement(name = "process-record-limit")
    @Mapping("processRecordLimit")
    protected int processRecordLimit;
    
    @XmlElement(name = "write-record-limit")
    @Mapping("writeRecordLimit")
    protected int writeRecordLimit;
    
    @XmlElement(name = "file-merge", required = true)
    @Mapping("fileMergeEnabled")
    protected boolean fileMerge;
    
    @XmlElement(name = "driver-list", required = true)
    @Mapping("this")
    protected DistributionServiceEntity.DriverList driverList;
    
    @XmlElement(required = true)
    @Mapping("serviceSchedulingParams")
    protected DistributionServiceEntity.Scheduling scheduling;
    
    @XmlElement(name = "file-grouping", required = true)
    @Mapping("fileGroupingParameter")
    protected DistributionServiceEntity.FileGrouping fileGrouping;
    
    @XmlElement(name = "store-cdr-file-summary-in-db", required = true)
    @Mapping("enableDBStats")
    protected String storeCdrFileSummaryInDb;

    
    public String getStartupMode() {
        return startupMode;
    }

    public void setStartupMode(String value) {
        this.startupMode = value;
    }

    
    public String getSortingCriteria() {
        return sortingCriteria;
    }

    
    public void setSortingCriteria(String value) {
        this.sortingCriteria = value;
    }

    
    public byte getExecutionInterval() {
        return executionInterval;
    }

    
    public void setExecutionInterval(byte value) {
        this.executionInterval = value;
    }

    
    public String getThirdPartyTransfer() {
        return thirdPartyTransfer;
    }

    
    public void setThirdPartyTransfer(String value) {
        this.thirdPartyTransfer = value;
    }

    
    public String getImmediateExecuteOnStartup() {
        return immediateExecuteOnStartup;
    }

    
    public void setImmediateExecuteOnStartup(String value) {
        this.immediateExecuteOnStartup = value;
    }

    
    public byte getMinimumThread() {
        return minimumThread;
    }

    
    public void setMinimumThread(byte value) {
        this.minimumThread = value;
    }

    
    public byte getMaximumThread() {
        return maximumThread;
    }

    
    public void setMaximumThread(byte value) {
        this.maximumThread = value;
    }

    
    public short getThreadQueueSize() {
        return threadQueueSize;
    }

    
    public void setThreadQueueSize(short value) {
        this.threadQueueSize = value;
    }

    
    public byte getFileBatchSize() {
        return fileBatchSize;
    }

    
    public void setFileBatchSize(byte value) {
        this.fileBatchSize = value;
    }

    
    public String getTimestenDatasourceName() {
        return timestenDatasourceName;
    }

    
    public void setTimestenDatasourceName(String value) {
        this.timestenDatasourceName = value;
    }

    
    public int getProcessRecordLimit() {
        return processRecordLimit;
    }

    
    public void setProcessRecordLimit(int value) {
        this.processRecordLimit = value;
    }

    
    public int getWriteRecordLimit() {
        return writeRecordLimit;
    }

    
    public void setWriteRecordLimit(int value) {
        this.writeRecordLimit = value;
    }

    
    
    public DistributionServiceEntity.DriverList getDriverList() {
        return driverList;
    }

    
    public void setDriverList(DistributionServiceEntity.DriverList value) {
        this.driverList = value;
    }

    
    public DistributionServiceEntity.Scheduling getScheduling() {
        return scheduling;
    }

    
    public void setScheduling(DistributionServiceEntity.Scheduling value) {
        this.scheduling = value;
    }

    
    public DistributionServiceEntity.FileGrouping getFileGrouping() {
        return fileGrouping;
    }

    
    public void setFileGrouping(DistributionServiceEntity.FileGrouping value) {
        this.fileGrouping = value;
    }

    
    public String getStoreCdrFileSummaryInDb() {
        return storeCdrFileSummaryInDb;
    }

    
    public void setStoreCdrFileSummaryInDb(String value) {
        this.storeCdrFileSummaryInDb = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "driver"
    })
    public static class DriverList {

    	
    	@XmlElement(required = true)
		@Mapping("myDrivers")
        protected List<DistributionServiceEntity.DriverList.Driver> driver;

        
        public List<DistributionServiceEntity.DriverList.Driver> getDriver() {
            if (driver == null) {
                driver = new ArrayList<>();
            }
            return this.driver;
        }


        
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "applicationOrder",
            "driverName",
            "enabled"
        })
        public static class Driver {

            @XmlElement(name = "application-order")
            @Mapping("applicationOrder")
            protected byte applicationOrder;
            
            
            @XmlElement(name = "driver-name", required = true)
            @Mapping("name")
            protected String driverName;
          
            @XmlElement(required = true)
            protected String enabled;

            
            public byte getApplicationOrder() {
                return applicationOrder;
            }

            
            public void setApplicationOrder(byte value) {
                this.applicationOrder = value;
            }

            
            public String getDriverName() {
                return driverName;
            }

            
            public void setDriverName(String value) {
                this.driverName = value;
            }

            
            public String getEnabled() {
                return enabled;
            }

            
            public void setEnabled(String value) {
                this.enabled = value;
            }

        }

    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mygroupingType",
        "forArchive",
        "archivePath"
    })
    public static class FileGrouping {

        @XmlElement(name = "grouping-type", required = true)
        protected String mygroupingType;
        
        @XmlElement(name = "for-archive", required = true)
        @Mapping("fileGroupEnable")
        protected boolean forArchive;
        
        @XmlElement(name = "archive-path", required = true)
        protected String archivePath;
        
        @XmlAttribute(name = "enabled")
        @Mapping("fileGroupEnable")
        protected boolean enabled;

        
        public String getArchivePath() {
            return archivePath;
        }
        
        public void setArchivePath(String value) {
            this.archivePath = value;
        }

		public boolean isForArchive() {
			return forArchive;
		}
		
		public boolean isEnabled() {
			return enabled;
		}

		public void setForArchive(boolean forArchive) {
			this.forArchive = forArchive;
		}

		public void setEnabled(boolean enabled) {
			this.enabled = enabled;
		}

		
		/**
		 * @return the mygroupingType
		 */
		public String getMygroupingType() {
			return mygroupingType;
		}

		
		/**
		 * @param mygroupingType the mygroupingType to set
		 */
		public void setMygroupingType(String mygroupingType) {
			this.mygroupingType = mygroupingType;
		}

        
      

    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "schedulingType",
        "schedulingTime",
        "schedulingDay",
        "schedulingDate"
    })
    public static class Scheduling {

        @XmlElement(name = "scheduling-type", required = true)
        @Mapping("schType")
        protected String schedulingType;
        
        @XmlElement(name = "scheduling-time", required = true)
        @XmlSchemaType(name = "time")
        @Mapping("time")
        protected XMLGregorianCalendar schedulingTime;
        
        @XmlElement(name = "scheduling-day")
    	@Mapping("day")
        protected byte schedulingDay;
        
        @XmlElement(name = "scheduling-date")
        @Mapping("date")
        protected byte schedulingDate;
        
        @XmlAttribute(name = "enabled")
        @Mapping("schedulingEnabled")
        protected boolean enabled;
        
        public String getSchedulingType() {
            return schedulingType;
        }

        
        public void setSchedulingType(String value) {
            this.schedulingType = value;
        }

        
        public XMLGregorianCalendar getSchedulingTime() {
            return schedulingTime;
        }

        
        public void setSchedulingTime(XMLGregorianCalendar value) {
            this.schedulingTime = value;
        }

        
        public byte getSchedulingDay() {
            return schedulingDay;
        }

        
        public void setSchedulingDay(byte value) {
            this.schedulingDay = value;
        }

        
        public byte getSchedulingDate() {
            return schedulingDate;
        }

        
        public void setSchedulingDate(byte value) {
            this.schedulingDate = value;
        }

		public boolean isEnabled() {
			return enabled;
		}

		public void setEnabled(boolean enabled) {
			this.enabled = enabled;
		}

       

    }



	
	/**
	 * @return the fileMerge
	 */
	public boolean isFileMerge() {
		return fileMerge;
	}


	
	/**
	 * @param fileMerge the fileMerge to set
	 */
	public void setFileMerge(boolean fileMerge) {
		this.fileMerge = fileMerge;
	}

	
	public String getMySortingType() {
		return mySortingType;
	}

	
	public void setMySortingType(String mySortingType) {
		this.mySortingType = mySortingType;
	}

}
