//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.31 at 03:23:28 PM IST 
//


package com.elitecore.sm.migration.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import org.dozer.Mapping;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "file-rename-agent")
public class FileRenameAgentEntity {

    @XmlElement(name = "initial-delay")
    @Mapping("initialDelay")
    protected int initialDelay;
    
    @XmlElement(name = "execution-interval")
    @Mapping("executionInterval")
    protected int executionInterval;
    
    @XmlElement(name = "service-list", required = true)
    @Mapping("this")
    protected FileRenameAgentEntity.ServiceList serviceList;

  
    public int getInitialDelay() {
        return initialDelay;
    }

   
    public void setInitialDelay(int value) {
        this.initialDelay = value;
    }

    
    public int getExecutionInterval() {
        return executionInterval;
    }

    /**
     * Sets the value of the executionInterval property.
     * 
     */
    public void setExecutionInterval(int value) {
        this.executionInterval = value;
    }

    
    public FileRenameAgentEntity.ServiceList getServiceList() {
        return serviceList;
    }

   
    public void setServiceList(FileRenameAgentEntity.ServiceList value) {
        this.serviceList = value;
    }


    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "service"
    })
    public static class ServiceList {

    	@Mapping("serviceList")
        protected List<FileRenameAgentEntity.ServiceList.Service> service;

        
        public List<FileRenameAgentEntity.ServiceList.Service> getService() {
            if (service == null) {
                service = new ArrayList<>();
            }
            return this.service;
        }


      
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Service {

            @XmlElement(required = true)
            @Mapping("service.svctype.alias")
            protected String name;
            
            @XmlElement(name = "dest-path", required = true)
            @Mapping("destinationPath")
            protected String destPath;
            
            @XmlElement(name = "file-extension-list", required = true)
            @Mapping("fileExtensitonList")
            protected String fileExtensionList;
            
            @XmlElement(name = "extension-after-rename", required = true)
            @Mapping("extAfterRename")
            protected String extensionAfterRename;
            
            @XmlElement(name = "character-renaming-operation", required = true)
            @Mapping("this")
            protected FileRenameAgentEntity.ServiceList.Service.CharacterRenamingOperation characterRenamingOperation;

           
            public String getName() {
                return name;
            }

            public void setName(String value) {
                this.name = value;
            }

           
            public String getDestPath() {
                return destPath;
            }

            public void setDestPath(String value) {
                this.destPath = value;
            }

          
            public String getFileExtensionList() {
                return fileExtensionList;
            }

           
            public void setFileExtensionList(String value) {
                this.fileExtensionList = value;
            }

            
            public String getExtensionAfterRename() {
                return extensionAfterRename;
            }

           
            public void setExtensionAfterRename(String value) {
                this.extensionAfterRename = value;
            }

            public FileRenameAgentEntity.ServiceList.Service.CharacterRenamingOperation getCharacterRenamingOperation() {
                return characterRenamingOperation;
            }

         
            public void setCharacterRenamingOperation(FileRenameAgentEntity.ServiceList.Service.CharacterRenamingOperation value) {
                this.characterRenamingOperation = value;
            }


          
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "character"
            })
            public static class CharacterRenamingOperation {

            	
            	@Mapping("charRenameOpList")
                protected List<FileRenameAgentEntity.ServiceList.Service.CharacterRenamingOperation.Character> character;
                
                @XmlAttribute(name = "enable")
                @Mapping("charRenameOperationEnable")
                protected String enable;

                
                public List<FileRenameAgentEntity.ServiceList.Service.CharacterRenamingOperation.Character> getCharacter() {
                    if (character == null) {
                        character = new ArrayList<>();
                    }
                    return this.character;
                }

               
                public String getEnable() {
                    return enable;
                }

                
                public void setEnable(String value) {
                    this.enable = value;
                }


               
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {

                })
                public static class Character {

                    @XmlElement(name = "sequence-no")
                    @Mapping("sequenceNo")
                    protected byte sequenceNo;
                    
                    @XmlElement(required = true)
                    protected String position;
                    
                    @XmlElement(name = "start-index", required = true)
                    @Mapping("startIndex")
                    protected String startIndex;
                    
                    @XmlElement(name = "end-index", required = true)
                    @Mapping("endIndex")
                    protected String endIndex;
                    
                    @XmlElement(required = true)
                    @Mapping("this")
                    protected FileRenameAgentEntity.ServiceList.Service.CharacterRenamingOperation.Character.Pedding pedding;
                    
                    @XmlElement(name = "default-value", required = true)
                    @Mapping("defaultValue")
                    protected String defaultValue;
                    
                    @XmlElement(required = true)
                    @Mapping("length")
                    protected String length;

                 
                    public byte getSequenceNo() {
                        return sequenceNo;
                    }

                    public void setSequenceNo(byte value) {
                        this.sequenceNo = value;
                    }

                    
                    public String getPosition() {
                        return position;
                    }

                    public void setPosition(String value) {
                        this.position = value;
                    }

                  
                    public String getStartIndex() {
                        return startIndex;
                    }

                   
                    public void setStartIndex(String value) {
                        this.startIndex = value;
                    }

                   
                    public String getEndIndex() {
                        return endIndex;
                    }

                   
                    public void setEndIndex(String value) {
                        this.endIndex = value;
                    }

                   
                    public FileRenameAgentEntity.ServiceList.Service.CharacterRenamingOperation.Character.Pedding getPedding() {
                        return pedding;
                    }

                   
                    public void setPedding(FileRenameAgentEntity.ServiceList.Service.CharacterRenamingOperation.Character.Pedding value) {
                        this.pedding = value;
                    }

                    public String getDefaultValue() {
                        return defaultValue;
                    }

                  
                    public void setDefaultValue(String value) {
                        this.defaultValue = value;
                    }

                   
                    public String getLength() {
                        return length;
                    }

                    public void setLength(String value) {
                        this.length = value;
                    }


                  
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Pedding {

                        @XmlValue
                        @Mapping("paddingType")
                        protected String value;
                        
                        @XmlAttribute(name = "type")
                        
                        protected String type;

                      
                        public String getValue() {
                            return value;
                        }

                       
                        public void setValue(String value) {
                            this.value = value;
                        }

                      
                        public String getType() {
                            return type;
                        }

                  
                        public void setType(String value) {
                            this.type = value;
                        }

                    }

                }

            }

        }

    }

}
