//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.11.02 at 06:45:50 PM IST
//

package com.elitecore.sm.migration.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import org.dozer.Mapping;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "serverId", "serviceList", "logging", "mediationRoot",
		"databaseDs", "fileStatisticsPath", "storeCdrFileSummaryInDb",
		"webServiceStatus", "minimumDiskSpaceRequired", "alerts" })
@XmlRootElement(name = "server-configuration")
public class ServerConfiguration {

	@XmlElement(name = "server-id")
	@Mapping("id")
	protected byte serverId;
	@XmlElement(name = "service-list", required = true)
	@Mapping("this")
	protected ServerConfiguration.ServiceList serviceList;
	
	@XmlElement(required = true)
	@Mapping("logsDetail")
	protected ServerConfiguration.Logging logging;
	
	@XmlElement(name = "mediation-root", required = true)
	@Mapping("mediationRoot")
	protected String mediationRoot;
	
	@XmlElement(name = "database-ds", required = true)
	@Mapping("this")
	protected ServerConfiguration.DatabaseDs databaseDs;
	
	@XmlElement(name = "file-statistics-path", required = true)
	@Mapping("fileStorageLocation")
	protected String fileStatisticsPath;
	
	@XmlElement(name = "store-cdr-file-summary-in-db", required = true)
	@Mapping("fileCdrSummaryDBEnable")
	protected String storeCdrFileSummaryInDb;
	
	@XmlElement(name = "web-service-status", required = true)
	protected String webServiceStatus;
	
	@XmlElement(name = "minimum-disk-space-required")
	@Mapping("minDiskSpace")
	protected byte minimumDiskSpaceRequired;
	
	@XmlElement(required = true)
	@Mapping("this")
	protected ServerConfiguration.Alerts alerts;

	public byte getServerId() {
		return serverId;
	}

	public void setServerId(byte value) {
		this.serverId = value;
	}

	public ServerConfiguration.ServiceList getServiceList() {
		return serviceList;
	}

	public void setServiceList(ServerConfiguration.ServiceList value) {
		this.serviceList = value;
	}

	public ServerConfiguration.Logging getLogging() {
		return logging;
	}

	public void setLogging(ServerConfiguration.Logging value) {
		this.logging = value;
	}

	public String getMediationRoot() {
		return mediationRoot;
	}

	public void setMediationRoot(String value) {
		this.mediationRoot = value;
	}

	public ServerConfiguration.DatabaseDs getDatabaseDs() {
		return databaseDs;
	}

	public void setDatabaseDs(ServerConfiguration.DatabaseDs value) {
		this.databaseDs = value;
	}

	public String getFileStatisticsPath() {
		return fileStatisticsPath;
	}

	public void setFileStatisticsPath(String value) {
		this.fileStatisticsPath = value;
	}

	public String getStoreCdrFileSummaryInDb() {
		return storeCdrFileSummaryInDb;
	}

	public void setStoreCdrFileSummaryInDb(String value) {
		this.storeCdrFileSummaryInDb = value;
	}

	public String getWebServiceStatus() {
		return webServiceStatus;
	}

	public void setWebServiceStatus(String value) {
		this.webServiceStatus = value;
	}

	public byte getMinimumDiskSpaceRequired() {
		return minimumDiskSpaceRequired;
	}

	public void setMinimumDiskSpaceRequired(byte value) {
		this.minimumDiskSpaceRequired = value;
	}

	public ServerConfiguration.Alerts getAlerts() {
		return alerts;
	}

	public void setAlerts(ServerConfiguration.Alerts value) {
		this.alerts = value;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "snmpAlert", "thresholdSystemAlert" })
	public static class Alerts {

		@XmlElement(name = "snmp-alert", required = true)
		protected String snmpAlert;
		
		@XmlElement(name = "threshold-system-alert", required = true)
		@Mapping("this")
		protected ServerConfiguration.Alerts.ThresholdSystemAlert thresholdSystemAlert;

		public String getSnmpAlert() {
			return snmpAlert;
		}

		public void setSnmpAlert(String value) {
			this.snmpAlert = value;
		}

		public ServerConfiguration.Alerts.ThresholdSystemAlert getThresholdSystemAlert() {
			return thresholdSystemAlert;
		}

		public void setThresholdSystemAlert(ServerConfiguration.Alerts.ThresholdSystemAlert value) {
			this.thresholdSystemAlert = value;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "timeInterval", "memory", "loadAverage" })
		public static class ThresholdSystemAlert {

			@XmlElement(name = "time-interval")
			@Mapping("thresholdTimeInterval")
			protected byte timeInterval;
			
			@Mapping("thresholdMemory")
			protected byte memory;
			
			@XmlElement(name = "load-average")
			@Mapping("loadAverage")
			protected byte loadAverage;
			
			@XmlAttribute(name = "enable")
			@Mapping("thresholdSysAlertEnable")
			protected boolean enable;

			public byte getTimeInterval() {
				return timeInterval;
			}

			public void setTimeInterval(byte value) {
				this.timeInterval = value;
			}

			public byte getMemory() {
				return memory;
			}

			public void setMemory(byte value) {
				this.memory = value;
			}

			public byte getLoadAverage() {
				return loadAverage;
			}

			public void setLoadAverage(byte value) {
				this.loadAverage = value;
			}

			
			/**
			 * @return the enable
			 */
			public boolean isEnable() {
				return enable;
			}

			
			/**
			 * @param enable the enable to set
			 */
			public void setEnable(boolean enable) {
				this.enable = enable;
			}

		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "datasourceName", "datasourceType" })
	public static class DatabaseDs {

		@XmlElement(name = "datasource-name", required = true)
		@Mapping("datasourceConfig.name")
		protected String datasourceName;
		
		@XmlElement(name = "datasource-type", required = true)
		@Mapping("datasourceConfig.type")
		protected String datasourceType;
		
		@XmlAttribute(name = "init")
		@Mapping("fileCdrSummaryDBEnable")
		protected boolean init;

		public String getDatasourceName() {
			return datasourceName;
		}

		public void setDatasourceName(String value) {
			this.datasourceName = value;
		}

		public String getDatasourceType() {
			return datasourceType;
		}

		public void setDatasourceType(String value) {
			this.datasourceType = value;
		}

		
		/**
		 * @return the init
		 */
		public boolean isInit() {
			return init;
		}

		
		/**
		 * @param init the init to set
		 */
		public void setInit(boolean init) {
			this.init = init;
		}

		

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "logLevel", "rolling", "location", "maxFileUnits" })
	public static class Logging {

		@XmlElement(name = "log-level", required = true)
		protected String logLevel;
		
		@XmlElement(name = "rolling", required = true)
		@Mapping("this")
		protected ServerConfiguration.Logging.Rolling rolling;
		
		@XmlElement(name = "max-file-units")
		@Mapping("maxRollingUnit")
		protected byte maxFileUnits;
		
		@XmlElement(required = true)
		@Mapping("logPathLocation")
		protected String location;

		public String getLogLevel() {
			return logLevel;
		}

		public void setLogLevel(String value) {
			this.logLevel = value;
		}

		public ServerConfiguration.Logging.Rolling getRolling() {
			return rolling;
		}

		public void setRolling(ServerConfiguration.Logging.Rolling value) {
			this.rolling = value;
		}

		public byte getMaxFileUnits() {
			return maxFileUnits;
		}

		public void setMaxFileUnits(byte value) {
			this.maxFileUnits = value;
		}

		public String getLocation() {
			return location;
		}

		public void setLocation(String value) {
			this.location = value;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "type","value" })
		public static class Rolling {

			@XmlValue
			protected String value;
			
			@XmlAttribute(name = "type")
			@Mapping("rollingType")
			protected String type;
			
			@XmlAttribute(name = "value")
			@Mapping("rollingValue")
			protected int valueAttribute;

			public String getValue() {
				return value;
			}

			public void setValue(String value) {
				this.value = value;
			}

			public String getType() {
				return type;
			}

			public void setType(String value) {
				this.type = value;
			}

			public int getValueAttribute() {
				return valueAttribute;
			}

			public void setValueAttribute(int value) {
				this.valueAttribute = value;
			}

		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "service" })
	public static class ServiceList {

		@Mapping("services")
		protected List<ServerConfiguration.ServiceList.Service> service;

		public List<ServerConfiguration.ServiceList.Service> getService() {
			if (service == null) {
				service = new ArrayList<>();
			}
			return this.service;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "serviceName", "serviceInstanceId",
				"serviceInstanceName", "enabled", "fileStatistics" })
		public static class Service {

			@XmlElement(name = "service-name", required = true)
			@Mapping("svctype.alias")
			protected String serviceName;
			
			@XmlElement(name = "service-instance-id")
			@Mapping("servInstanceId")
			protected String serviceInstanceId;
			
			@XmlElement(name = "service-instance-name", required = true)
			@Mapping("name")
			protected String serviceInstanceName;
			
			@XmlElement(required = true)
			protected String enabled;
			
			@XmlElement(name = "file-statistics", required = true)
			@Mapping("enableFileStats")
			protected boolean fileStatistics;

			public String getServiceName() {
				return serviceName;
			}

			public void setServiceName(String value) {
				this.serviceName = value;
			}

			public String getServiceInstanceId() {
				return serviceInstanceId;
			}

			public void setServiceInstanceId(String value) {
				this.serviceInstanceId = value;
			}

			public String getServiceInstanceName() {
				return serviceInstanceName;
			}

			public void setServiceInstanceName(String value) {
				this.serviceInstanceName = value;
			}

			public String getEnabled() {
				return enabled;
			}

			public void setEnabled(String value) {
				this.enabled = value;
			}
			
			public boolean isFileStatistics() {
				return fileStatistics;
			}

			public void setFileStatistics(boolean fileStatistics) {
				this.fileStatistics = fileStatistics;
			}

			
		}

	}

}
