/**
 * 
 */
package com.elitecore.sm.common.constants;

/**
 * @author Ranjitsinh Reval
 * 2 Feb,2016
 *
 */
public final class  AuditConstants {
	

	/* Login Actions */
	public static final String LOGIN_ACTION = "LOGIN_ACTION";
	public static final String LOGOUT_ACTION = "LOGOUT_ACTION";	
	public static final String LOGIN_AS_LDAP = "LOGIN_AS_LDAP";
	public static final String LOGIN_AS_LDAP_DENIED = "LOGIN_AS_LDAP_DENIED";
	public static final String LOGIN_AS_SSO_DENIED = "LOGIN_AS_SSO_DENIED";
	public static final String ERROR_LOGIN_AS_LDAP = "ERROR_LOGIN_AS_LDAP";
	public static final String NOT_LDAP_STAFF = "NOT_LDAP_STAFF";
	
	/* All Server Manager Actions Start Here */
	public static final String CREATE_SERVER = "CREATE_SERVER";
	public static final String UPDATE_SERVER = "UPDATE_SERVER";
	public static final String DELETE_SERVER = "DELETE_SERVER";	

	public static final String CREATE_SERVER_INSTANCE = "CREATE_SERVER_INSTANCE";
	public static final String UPDATE_SERVER_INSTANCE_ADVANCE_CONFIGURATION = "UPDATE_SERVER_INSTANCE_ADVANCE_CONFIGURATION";
	public static final String UPDATE_SERVER_INSTANCE_SYSTEMLOG = "UPDATE_SERVER_INSTANCE_SYSTEMLOG";
	public static final String UPDATE_SERVER_INSTANCE_STATISTICS = "UPDATE_SERVER_INSTANCE_STATISTICS";
	public static final String DELETE_SERVER_INSTANCE = "DELETE_SERVER_INSTANCE";

	public static final String IMPORT_SERVER_INSTANCE_CONFIGURATION = "IMPORT_SERVER_INSTANCE_CONFIGURATION";
	public static final String EXPORT_SERVER_INSTANCE_CONFIGURATION = "EXPORT_SERVER_INSTANCE_CONFIGURATION";
	public static final String SYNCHRONIZE_SERVER_INSTANCE_ACTION = "SYNCHRONIZE_SERVER_INSTANCE_ACTION";
	public static final String SOFT_RESTART_SERVER_INSTANCE_CONFIGURATION = "SOFT_RESTART_SERVER_INSTANCE_CONFIGURATION";
	public static final String RELOAD_SERVER_INSTANCE_CONFIGURATION = "RELOAD_SERVER_INSTANCE_CONFIGURATION";
	public static final String RELOAD_SERVER_INSTANCE_CACHE = "RELOAD_SERVER_INSTANCE_CACHE";
	public static final String START_SERVER_INSTANCE = "START_SERVER_INSTANCE";
	public static final String STOP_SERVER_INSTANCE = "STOP_SERVER_INSTANCE";
	public static final String RESTART_SERVER_INSTANCE = "RESTART_SERVER_INSTANCE";
	public static final String COPY_CONFIG_SERVER_INSTANCE = "COPY_CONFIG_SERVER_INSTANCE";

	/*not yet used*/
	
	public static final String UPLOAD_SERVER_REPROCESS_FILE = "UPLOAD_SERVER_REPROCESS_FILE";
	public static final String DOWNLOAD_SERVER_REPROCESS_FILE = "DOWNLOAD_SERVER_REPROCESS_FILE";
	public static final String MARK_SERVER_REPROCESS_FILE = "MARK_SERVER_REPROCESS_FILE";
	public static final String MANUAL_COLLECTION_SERVER_FILE = "MANUAL_COLLECTION_SERVER_FILE";
	public static final String UPDATE_SERVICE_BASIC_DETAILS = "UPDATE_SERVICE_BASIC_DETAILS";
	public static final String CREATE_POLICY = "CREATE_POLICY";
	public static final String UPDATE_POLICY = "UPDATE_POLICY";
	public static final String DELETE_POLICY = "DELETE_POLICY";
	public static final String EXPORT_POLICY = "EXPORT_POLICY";
	public static final String IMPORT_POLICY = "IMPORT_POLICY";
	public static final String CREATE_POLICY_RULE_GROUP = "CREATE_POLICY_RULE_GROUP";
	public static final String UPDATE_POLICY_RULE_GROUP = "UPDATE_POLICY_RULE_GROUP";
	public static final String DELETE_POLICY_RULE_GROUP = "DELETE_POLICY_RULE_GROUP";
	public static final String CREATE_POLICY_RULE = "CREATE_POLICY_RULE";
	public static final String UPDATE_POLICY_RULE = "UPDATE_POLICY_RULE";
	public static final String DELETE_POLICY_RULE = "DELETE_POLICY_RULE";
	public static final String CREATE_POLICY_CONDITION = "CREATE_POLICY_CONDITION";
	public static final String UPDATE_POLICY_CONDITION = "UPDATE_POLICY_CONDITION";
	public static final String DELETE_POLICY_CONDITION = "DELETE_POLICY_CONDITION";
	public static final String CREATE_POLICY_ACTION = "CREATE_POLICY_ACTION";
	public static final String UPDATE_POLICY_ACTION = "UPDATE_POLICY_ACTION";
	public static final String DELETE_POLICY_ACTION = "DELETE_POLICY_ACTION";
	public static final String ADD_SERVER_DATABASE_QUERY = "ADD_SERVER_DATABASE_QUERY";
	public static final String UPDATE_SERVER_DATABASE_QUERY = "UPDATE_SERVER_DATABASE_QUERY";
	public static final String REMOVE_SERVER_DATABASE_QUERY = "REMOVE_SERVER_DATABASE_QUERY";
	public static final String UPDATE_SERVER_DATASOURCE_CONFIGURATION = "UPDATE_SERVER_DATASOURCE_CONFIGURATION";
	public static final String UPDATE_JNDI_PROPERTIES_CONFIGURATION = "UPDATE_JNDI_PROPERTIES_CONFIGURATION";

	/* All Service manager Actions Start Here */
	public static final String CREATE_SERVICE = "CREATE_SERVICE";
	public static final String UPDATE_SERVICE_CONFIGURATION = "UPDATE_SERVICE_CONFIGURATION";
	public static final String DELETE_SERVICE = "DELETE_SERVICE";
	public static final String SYNCHRONIZE_SERVICE = "SYNCHRONIZE_SERVICE";
	public static final String IMPORT_SERVICE_CONFIGURATION = "IMPORT_SERVICE_CONFIGURATION";
	public static final String EXPORT_SERVICE_CONFIGURATION = "EXPORT_SERVICE_CONFIGURATION";
	public static final String START_SERVICE = "START_SERVICE";
	public static final String STOP_SERVICE = "STOP_SERVICE";
	public static final String UPDATE_SERVICE_STATUS = "UPDATE_SERVICE_STATUS";

	/* Driver Actions start here */
	public static final String CREATE_DRIVER = "CREATE_DRIVER";
	public static final String UPDATE_DRIVER = "UPDATE_DRIVER";

	public static final String DELETE_DRIVER = "DELETE_DRIVER";	
	public static final String UPDATE_DRIVER_STATUS = "UPDATE_DRIVER_STATUS";
	public static final String UPDATE_DRIVER_APLICATION_ORDER = "UPDATE_DRIVER_APLICATION_ORDER";
	
	public static final String CREATE_CLIENT = "CREATE_CLIENT";
	public static final String UPDATE_CLIENT = "UPDATE_CLIENT";
	public static final String DELETE_CLIENT = "DELETE_CLIENT";	
	public static final String UPDATE_CLIENT_STATUS = "UPDATE_CLIENT_STATUS";

	public static final String CREATE_PATHLIST = "CREATE_PATHLIST";	
	public static final String UPDATE_PATHLIST = "UPDATE_PATHLIST";	
	public static final String DELETE_PATHLIST = "DELETE_PATHLIST";	
	
	public static final String CREATE_MISSINGFILESEQUENCEMGMT = "CREATE_MISSINGFILESEQUENCEMGMT";	
	public static final String UPDATE_MISSINGFILESEQUENCEMGMT = "UPDATE_MISSINGFILESEQUENCEMGMT";	
	public static final String DELETE_MISSINGFILESEQUENCEMGMT = "DELETE_MISSINGFILESEQUENCEMGMT";
	
	public static final String CREATE_CONSOLIDATION_DEFINITION = "CREATE_CONSOLIDATION_DEFINITION";
	public static final String UPDATE_CONSOLIDATION_DEFINITION = "UPDATE_CONSOLIDATION_DEFINITION";
	public static final String DELETE_CONSOLIDATION_DEFINITION = "DELETE_CONSOLIDATION_DEFINITION";
	
	public static final String CREATE_CONSOLIDATION_DEFINITION_GROUP = "CREATE_CONSOLIDATION_DEFINITION_GROUP";
	public static final String UPDATE_CONSOLIDATION_DEFINITION_GROUP = "UPDATE_CONSOLIDATION_DEFINITION_GROUP";
	
	
	public static final String CREATE_CONSOLIDATION_DEFINITION_ATTRIBUTE = "CREATE_CONSOLIDATION_DEFINITION_ATTRIBUTE";
	public static final String UPDATE_CONSOLIDATION_DEFINITION_ATTRIBUTE = "UPDATE_CONSOLIDATION_DEFINITION_ATTRIBUTE";
	
	public static final String CREATE_AGGREGATION_DEFINATION = "CREATE_AGGREGATION_DEFINATION";
	public static final String UPDATE_AGGREGATION_DEFINATION = "UPDATE_AGGREGATION_DEFINATION";
	
	public static final String CREATE_PARSER = "CREATE_PARSER";	
	public static final String UPDATE_PARSER = "UPDATE_PARSER";	
	public static final String DELETE_PARSER = "DELETE_PARSER";
	public static final String CLONE_PARSER = "CLONE_PARSER";	
	
	public static final String CREATE_COMPOSER = "CREATE_COMPOSER";	
	public static final String UPDATE_COMPOSER = "UPDATE_COMPOSER";	
	public static final String DELETE_COMPOSER = "DELETE_COMPOSER";	
	
	// All Staff Manger Actions Start here

	public static final String CREATE_STAFF = "CREATE_STAFF";
	public static final String DELETE_STAFF = "DELETE_STAFF";
	public static final String UPDATE_STAFF_STATUS = "UPDATE_STAFF_STATUS";
	public static final String UPDATE_STAFF_DETAILS = "UPDATE_STAFF_DETAILS";
	public static final String UPDATE_STAFF_ACCESS_GROUP = "UPDATE_STAFF_ACCESS_GROUP";
	public static final String UPDATE_STAFF_USERNAME = "UPDATE_STAFF_USERNAME";
	public static final String UPDATE_STAFF_PASSWORD = "UPDATE_STAFF_PASSWORD"; //NOSONAR
	public static final String CREATE_ACCESS_GROUP = "CREATE_ACCESS_GROUP";
	public static final String DELETE_ACCESS_GROUP = "DELETE_ACCESS_GROUP";
	public static final String UPDATE_ACCESS_GROUP = "UPDATE_ACCESS_GROUP";

	// all System Manager Actions Start Here
	public static final String UPDATE_GENERAL_PARAMETER = "UPDATE_GENERAL_PARAMETER";
	public static final String UPDATE_PASSWORD_POLICY = "UPDATE_PASSWORD_POLICY"; //NOSONAR
	public static final String UPDATE_CUSTOMER_DETAILS = "UPDATE_CUSTOMER_DETAILS";
	public static final String UPDATE_FILE_REPROCESSING = "UPDATE_FILE_REPROCESSING";
	public static final String UPDATE_CUSTOMER_LOGO = "UPDATE_CUSTOMER_LOGO";
	
	public static final String INVALID_LOGIN = "INVALID_LOGIN";
	public static final String LOCKED_LOGIN_DENIED = "LOCKED_LOGIN_DENIED";
	public static final String UNAUTHORIZED_IP_LOGIN_DENIED = "UNAUTHORIZED_IP_LOGIN_DENIED";
	public static final String DISABLED_LOGIN_DENIED = "DISABLED_LOGIN_DENIED";
	

	//All SNMP Action starts here..
	public static final String ADD_SNMP_CLIENT_CONFIGURATION = "ADD_SNMP_CLIENT_CONFIGURATION";
	public static final String UPDATE_SNMP_CLIENT_CONFIGURATION = "UPDATE_SNMP_CLIENT_CONFIGURATION";
	public static final String DELETE_SNMP_CLIENT_CONFIGURATION = "DELETE_SNMP_CLIENT_CONFIGURATION";
	public static final String GET_SNMP_ALERT_CONFIGURATION = "GET_SNMP_ALERT_CONFIGURATION";
	
	public static final String ADD_SNMP_ALERT_LISTENER_CONFIGURATION = "ADD_SNMP_ALERT_LISTENER_CONFIGURATION";
	public static final String UPDATE_SNMP_ALERT_LISTENER_CONFIGURATION = "UPDATE_SNMP_ALERT_LISTENER_CONFIGURATION";
	
	// ALL Agent audit constants start here.
	public static final String UPDATE_DATEBASE_REPROCESS_AGENT = "UPDATE_DATEBASE_REPROCESS_AGENT";
	public static final String UPDATE_FILE_RENAME_AGENT = "UPDATE_FILE_RENAME_AGENT";
	public static final String UPDATE_FILE_DISTRIBUTION_AGENT = "UPDATE_FILE_DISTRIBUTION_AGENT";
	public static final String UPDATE_PACKATE_STATISTIC_AGENT = "UPDATE_PACKATE_STATISTIC_AGENT";
	
	public static final String CREATE_MAPPING = "CREATE_MAPPING";
	public static final String UPDATE_MAPPING = "UPDATE_MAPPING";
	public static final String DELETE_MAPPING = "DELETE_MAPPING";
	
	public static final String CREATE_PARSER_ATTRIBUTE = "CREATE_PARSER_ATTRIBUTE";
	public static final String DELETE_PARSER_ATTRIBUTE = "DELETE_PARSER_ATTRIBUTE";
	public static final String UPDATE_PARSER_ATTRIBUTE = "UPDATE_PARSER_ATTRIBUTE";
	public static final String UPDATE_PARSER_GROUP_ATTRIBUTE = "UPDATE_PARSER_GROUP_ATTRIBUTE";
	
	public static final String CREATE_COMPOSER_ATTRIBUTE = "CREATE_COMPOSER_ATTRIBUTE";	
	public static final String DELETE_COMPOSER_ATTRIBUTE = "DELETE_COMPOSER_ATTRIBUTE";
	public static final String UPDATE_COMPOSER_ATTRIBUTE = "UPDATE_COMPOSER_ATTRIBUTE";
	
	public static final String CREATE_DATASOURCE = "CREATE_DATASOURCE";
	public static final String UPDATE_DATASOURCE = "UPDATE_DATASOURCE";
	public static final String DELETE_DATASOURCE = "DELETE_DATASOURCE";
	
	public static final String CREATE_KAFKA_DATASOURCE = "CREATE_KAFKA_DATASOURCE";
	public static final String UPDATE_KAFKA_DATASOURCE = "UPDATE_KAFKA_DATASOURCE";
	public static final String DELETE_KAFKA_DATASOURCE = "DELETE_KAFKA_DATASOURCE";

	public static final String CREATE_DEVICE = "CREATE_DEVICE";
	public static final String UPDATE_DEVICE = "UPDATE_DEVICE";
	public static final String DELETE_DEVICE = "DELETE_DEVICE";

	public static final String UPDATE_AGENT = "UPDATE_AGENT";
	public static final String UPDATE_AGENT_DETAILS = "UPDATE_AGENT_DETAILS";
	public static final String UPDATE_AGENT_STATUS = "UPDATE_AGENT_STATUS";
	public static final String CREATE_AGENT = "CREATE_AGENT";
	public static final String DELETE_AGENT = "DELETE_AGENT";
	public static final String UPDATE_FILERENAMEAGENT_STATUS = "UPDATE_FILERENAMEAGENT_STATUS";

	public static final String CREATE_CHAR_RENAME = "CREATE_CHAR_RENAME";
	public static final String UPDATE_CHAR_RENAME = "UPDATE_CHAR_RENAME";
	public static final String DELETE_CHAR_RENAME = "DELETE_CHAR_RENAME";

	public static final String CREATE_SNMP_ALERT = "CREATE_SNMP_ALERT";
	public static final String CREATE_SNMP_SERVER = "CREATE_SNMP_SERVER";
	public static final String DELETE_SNMP_SERVER = "DELETE_SNMP_SERVER";
	
	public static final String UPDATE_SNMP_SERVER_STATUS = "UPDATE_SNMP_SERVER_STATUS";	
	
	public static final String UPDATE_SNMP_ALERT_LIST = "UPDATE_SNMP_ALERT_LIST";
	
	public static final String ADD_SNMP_CONFIGURATION = "ADD_SNMP_CONFIGURATION";
	public static final String UPDATE_SNMP_SERVER_CONFIGURATION = "UPDATE_SNMP_SERVER_CONFIGURATION";
	public static final String UPDATE_SNMP_ALERT_STATUS = "UPDATE_SNMP_ALERT_STATUS";
	
	public static final String UPDATE_SNMP_CLIENT_STATUS = "UPDATE_SNMP_CLIENT_STATUS";
	public static final String UPDATE_SNMP_ALERTS_TO_CLIENT = "UPDATE_SNMP_ALERTS_TO_CLIENT";	

	public static final String UPDATE_PRODUCT_CONFIGURATION = "UPDATE_PRODUCT_CONFIGURATION";
	public static final String UPDATE_PROFILE_CONFIGURATION = "UPDATE_PROFILE_CONFIGURATION";
	public static final String UPDATE_PROFILE_ACCESSGROUP_CONFIGURATION = "UPDATE_PROFILE_ACCESSGROUP_CONFIGURATION";
	public static final String UPDATE_PROFILE_BUSINESS_SUB_CONFIGURATION = "UPDATE_PROFILE_BUSINESS_SUB_CONFIGURATION";
	public static final String UPDATE_PROFILE_BUSINESS_CONFIGURATION = "UPDATE_PROFILE_BUSINESS_CONFIGURATION";	
	
	public static final String CREATE_IPLOG_PATHLIST = "CREATE_IPLOG_PATHLIST";
	public static final String UPDATE_IPLOG_PATHLIST = "UPDATE_IPLOG_PATHLIST";
	public static final String DELETE_IPLOG_PATHLIST = "DELETE_IPLOG_PATHLIST";

	public static final String CREATE_PARSING_PATHLIST = "CREATE_PARSING_PATHLIST";
	public static final String UPDATE_PARSING_PATHLIST = "UPDATE_PARSING_PATHLIST";
	public static final String DELETE_PARSING_PATHLIST = "DELETE_PARSING_PATHLIST";
	
	public static final String UPDATE_IPLOG_HASH_CONFIGURATION = "UPDATE_IPLOG_HASH_CONFIGURATION";	

	public static final String UPDATE_PARTITION_PARAM = "UPDATE_PARTITION_PARAM";
	
	public static final String UPDATE_THRESHOLD_SERVER_INSTANCE = "UPDATE_THRESHOLD_SERVER_INSTANCE";
	public static final String UPDATE_THRESHOLD_GENERIC = "UPDATE_THRESHOLD_GENERIC";
	public static final String UPDATE_THRESHOLD_SERVICE = "UPDATE_THRESHOLD_SERVICE";
	
	public static final String CREATE_SERVICE_TO_FILE_RENAME_AGENT = "CREATE_SERVICE_TO_FILE_RENAME_AGENT";
	public static final String UPDATE_SERVICE_TO_FILE_RENAME_AGENT = "UPDATE_SERVICE_TO_FILE_RENAME_AGENT";
	public static final String UPDATE_FILE_RENAME_AGENT_DETAILS = "UPDATE_FILE_RENAME_AGENT_DETAILS";	
	public static final String DELETE_SERVICE_FROM_FILE_RENAME_AGENT = "DELETE_SERVICE_FROM_FILE_RENAME_AGENT";
	
	public static final String CREATE_CHAR_RENAME_TO_FILE_RENAME_AGENT = "CREATE_CHAR_RENAME_TO_FILE_RENAME_AGENT";	
	public static final String UPDATE_CHAR_RENAME_TO_FILE_RENAME_AGENT = "UPDATE_CHAR_RENAME_TO_FILE_RENAME_AGENT";		
	public static final String DELETE_CHAR_RENAME_TO_FILE_RENAME_AGENT = "DELETE_CHAR_RENAME_TO_FILE_RENAME_AGENT";	
	
	
	public static final String CREATE_CONSOLIDATION_MAPPING = "CREATE_CONSOL_MAPPING";
	public static final String DELETE_CONSOLIDATION_MAPPING = "DELETE_CONSOL_MAPPING";
	public static final String UPDATE_CONSOLIDATION_MAPPING = "UPDATE_CONSOL_MAPPING";
	
	public static final String UPDATE_COMPOSER_BASIC_MAPPING_DETAIL = "UPDATE_COMPOSER_BASIC_MAPPING_DETAIL";
	public static final String CREATE_DATABASE_DISTRIBUTION_DRIVER_ATTRIBUTE = "CREATE_DATABASE_DISTRIBUTION_DRIVER_ATTRIBUTE";
	public static final String UPDATE_DATABASE_DISTRIBUTION_DRIVER_ATTRIBUTE = "UPDATE_DATABASE_DISTRIBUTION_DRIVER_ATTRIBUTE";
	public static final String DELETE_DATABASE_DISTRIBUTION_DRIVER_ATTRIBUTE = "DELETE_DATABASE_DISTRIBUTION_DRIVER_ATTRIBUTE";
	
	public static final String CREATE_DATABASE_QUERY = "CREATE_DATABASE_QUERY";
	public static final String UPDATE_DATABASE_QUERY = "UPDATE_DATABASE_QUERY";
	public static final String DELETE_DATABASE_QUERY = "DELETE_DATABASE_QUERY";
	
	public static final String DELETE_RULE_LOOKUP_TABLE = "DELETE_RULE_LOOKUP_TABLE";
	public static final String CREATE_RULE_LOOKUP_TABLE = "CREATE_RULE_LOOKUP_TABLE";
	public static final String UPDATE_RULE_LOOKUP_TABLE = "UPDATE_RULE_LOOKUP_TABLE";
	public static final String UPDATE_RULE_LOOKUP_FIELD_LIST = "UPDATE_RULE_LOOKUP_FIELD_LIST";
	public static final String DATA_UPLOADED_FOR_RULE_LOOKUP = "DATA_UPLOADED_FOR_RULE_LOOKUP";
	public static final String DATA_DOWNLOADED_FOR_RULE_LOOKUP = "DATA_DOWNLOADED_FOR_RULE_LOOKUP";

	public static final String UPDATE_PARSER_MAPPING_DETAILS= "UPDATE_PARSER_MAPPING_DETAILS";

	public static final String UPDATE_COMPOSER_MAPPING_DETAIL = "UPDATE_COMPOSER_MAPPING_DETAIL";
	public static final String GENERATE_SERVICEWISE_SUMMARY = "GENERATE_SERVICEWISE_SUMMARY";
	//public static final String UPDATE_PARSER_MAPPING_DETAILS = "UPDATE_PARSER_MAPPING_DETAILS";

	
	public static final String FILE_REPROCESS_BULK_EDIT = "BULK_EDIT";
	public static final String FILE_REPROCESS_DIRECT_REPROCESS = "DIRECT_REPROCESS";
	public static final String FILE_ARCHIVE_RESTORE = "ARCHIVE_RESTORE";
	public static final String FILE_REPROCESS_DELETE_FILE = "DELETE_FILE";
	public static final String FILE_REPROCESS_UPLOAD_REPROCESS = "UPLOAD_REPROCESS";
	public static final String FILE_REPROCESS_REVERT_TO_ORIGINAL = "REVERT_TO_ORIGINAL";
	
	public static final String SM_FULL_LICENSE = "SM_FULL_LICENSE";
	public static final String SM_TRIAL_LICENSE = "SM_TRIAL_LICENSE";
	public static final String ENGINE_FULL_LICENSE = "ENGINE_FULL_LICENSE";
	public static final String UPGRADE_DEFAULT_LICENSE = "UPGRADE_DEFAULT_LICENSE";
	
	public static final String UPDATE_HOST_CONFIGURATION = "UPDATE_HOST_CONFIGURATION";
	public static final String UPDATE_ROAMING_PARAMETER="UPDATE_ROAMING_PARAMETER";
	public static final String UPDATE_FILE_SEQUENCE_MANAGEMENT="UPDATE_FILE_SEQUENCE_MANAGEMENT";
	public static final String UPDATE_TEST_SIM_MANAGEMNT = "UPDATE_TEST_SIM_MANAGEMENT";
	public static final String UPDATE_FILE_MANAGEMENT = "UPDATE_FILE_MANAGEMENT";
	public static final String LDAP_USER_NOT_FOUND = "LDAP_USER_NOT_FOUND";
	public static final String LDAP_CREDENTIALS_NOT_VALID = "LDAP_CREDENTIALS_NOT_VALID";
	public static final String LDAP_ACCOUNT_LOCKED = "LDAP_ACCOUNT_LOCKED";
	public static final String LDAP_ACCOUNT_EXPIRED = "LDAP_ACCOUNT_EXPIRED";
	public static final String LDAP_ACCOUNT_DISABLED = "LDAP_ACCOUNT_DISABLED";
	public static final String LDAP_PASSWORD_EXPIRED = "LDAP_PASSWORD_EXPIRED";//NOSONAR
	public static final String LOGIN_AS_LDAP_SUCCESS = "LOGIN_AS_LDAP_SUCCESS";
	public static final String PUBLISH_SERVER_INSTANCE = "PUBLISH_SERVER_INSTANCE";
	public static final String RESTORE_SERVER_INSTANCE = "RESTORE_SERVER_INSTANCE";
	
	public static final String UPDATE_SCRIPT = "SCRIPT_UPDATE";
	public static final String EXECUTE_SCRIPT = "SCRIPT_EXECUTE";
	
	public static final String CREATE_CIRCLE = "CREATE_CIRCLE";
	public static final String UPDATE_CIRCLE = "UPDATE_CIRCLE";
	public static final String DELETE_CIRCLE = "DELETE_CIRCLE";
	public static final String UPLOAD_LICENSE = "UPLOAD_LICENSE";
	
	private AuditConstants(){
		// Default constructor
	}

	
}