/**
 * 
 */
package com.elitecore.sm.common.constants;


/**
 * @author Sunil Gulabani
 * Jul 22, 2015
 */
public interface EngineConstants {
	
	public static String MEDIATION_SERVER = "MEDIATION_SERVER" ;
	public static String ORACLE_DATABASE_CONFIGURATION = "ORACLE_DATABASE_CONFIGURATION" ;
	public static String KAFKA_CONFIGURATION = "KAFKA_CONFIGURATION";
	public static String JNDI_PROPERTIES_CONFIGURATION = "JNDI_PROPERTIES_CONFIGURATION";
	public static String POLICIES_CONFIGURATION = "POLICIES_CONFIGURATION";
	public static String POLICY_GROUPS_CONFIGURATION = "POLICY_GROUPS_CONFIGURATION";
	public static String POLICY_RULES_CONFIGURATION = "POLICY_RULES_CONFIGURATION";
	public static String POLICY_CONDITIONS_CONFIGURATION = "POLICY_CONDITIONS_CONFIGURATION";
	public static String POLICY_ACTIONS_CONFIGURATION = "POLICY_ACTIONS_CONFIGURATION";
	public static String DATABASE_QUERIES_CONFIGURATION = "DATABASE_QUERIES_CONFIGURATION";
	public static String SNMP_ALERT_LISTENER_CONFIGURATION = "SNMP_ALERT_LISTENER_CONFIGURATION";
	public static String ALERT_CONFIGURATION = "ALERT_CONFIGURATION";
	public static String SNMP_CONFIGURATION = "SNMP_CONFIGURATION";
	public static String FILE_RENAMING_AGENT = "FILE_RENAMING_AGENT";
	public static String FILE_DISTRIBUTION_AGENT = "FILE_DISTRIBUTION_AGENT";
	public static String PACKET_STATISTICS_AGENT = "PACKET_STATISTICS_AGENT";
	public static String WEB_SERVICE_CONFIGURATION = "WEB_SERVICE_CONFIGURATION";
	public static String PLUGGABLE_AGGREGATION_CONFIGURATION = "PLUGGABLE_AGGREGATION_CONFIGURATION";
	
	
	// Parsing Service
	public static String PARSING_SERVICE = "PARSING_SERVICE";
	public static String ASCII_PARSING_PLUGIN = "ASCII_PARSING_PLUGIN" ;
	public static String MTSIEMENS_BINARY_PARSING_PLUGIN = "MTSIEMENS_BINARY_PARSING_PLUGIN";
	public static String FIXED_LENGTH_ASCII_PARSING_PLUGIN = "FIXED_LENGTH_ASCII_PARSING_PLUGIN";
	public static String DETAIL_LOCAL_PARSING_PLUGIN = "DETAIL_LOCAL_PARSING_PLUGIN" ;
	public static String XML_PARSING_PLUGIN = "XML_PARSING_PLUGIN";
	public static String SSTP_XML_PARSING_PLUGIN = "SSTP_XML_PARSING_PLUGIN" ;
	public static String DIGITEL_BINARY_PARSING_PLUGIN = "DIGITEL_BINARY_PARSING_PLUGIN" ;
	public static String ASN1_PARSING_PLUGIN = "ASN1_PARSING_PLUGIN" ;
	public static String MT_ALCATEL_BINARY_PARSING_PLUGIN = "MT_ALCATEL_BINARY_PARSING_PLUGIN" ;
	public static String MT_SIEMENS_BINARY_PARSING_PLUGIN = "MT_SIEMENS_BINARY_PARSING_PLUGIN" ;
	public static String NATFLOW_PARSING_PLUGIN = "NATFLOW_PARSING_PLUGIN" ;
	public static String NATFLOW_ASN_PARSING_PLUGIN = "NATFLOW_ASN_PARSING_PLUGIN" ;
	public static String REGEX_PARSING_PLUGIN = "REGEX_PARSING_PLUGIN" ;
	public static String HTML_PARSING_PLUGIN = "HTML_PARSING_PLUGIN" ;
	public static String XLS_PARSING_PLUGIN = "XLS_PARSING_PLUGIN" ;
	public static String VARIABLE_LENGTH_ASCII_PARSING_PLUGIN = "VARIABLE_LENGTH_ASCII_PARSING_PLUGIN" ;
	public static String VARIABLE_LENGTH_BINARY_PARSING_PLUGIN = "VARIABLE_LENGTH_BINARY_PARSING_PLUGIN" ;
	public static String JSON_PARSING_PLUGIN = "JSON_PARSING_PLUGIN" ;
	
	public static String UNIX_EPOCH_TIME = "Unix Epoch";
	
	
	// Processing Service
	public static String PROCESSING_SERVICE = "PROCESSING_SERVICE";

	// Distribution Service
	public static String DISTRIBUTION_SERVICE = "DISTRIBUTION_SERVICE";
	public static String FTP_DISTRIBUTION_DRIVER = "FTP_DISTRIBUTION_DRIVER";
	public static String HADOOP_DISTRIBUTION_DRIVER="HADOOP_DISTRIBUTION_DRIVER";
	public static String LOCAL_DISTRIBUTION_DRIVER="LOCAL_DISTRIBUTION_DRIVER";
	public static String SFTP_DISTRIBUTION_DRIVER="SFTP_DISTRIBUTION_DRIVER";
	public static String DATABASE_DISTRIBUTION_DRIVER="DATABASE_DISTRIBUTION_DRIVER";
	
	public static String DETAIL_LOCAL_COMPOSER_PLUGIN = "DETAIL_LOCAL_COMPOSER_PLUGIN" ;
	public static String ASCII_COMPOSER_PLUGIN = "ASCII_COMPOSER_PLUGIN" ;
	public static String FIXED_LENGTH_ASCII_COMPOSER_PLUGIN = "FIXED_LENGTH_ASCII_COMPOSER_PLUGIN" ;
	public static String ASN1_COMPOSER_PLUGIN = "ASN1_COMPOSER_PLUGIN" ;
	public static String XML_COMPOSER_PLUGIN = "XML_COMPOSER_PLUGIN" ;
	public static String DEFAULT_COMPOSER_PLUGIN = "DEFAULT_COMPOSER_PLUGIN" ;
	public static String RAP_COMPOSER_PLUGIN = "RAP_COMPOSER_PLUGIN" ;
	public static String TAP_COMPOSER_PLUGIN = "TAP_COMPOSER_PLUGIN" ;
	public static String NRTRDE_COMPOSER_PLUGIN = "NRTRDE_COMPOSER_PLUGIN" ;
	
	public static String COLLECTION_SERVICE = "COLLECTION_SERVICE" ; 
	public static String LOCAL_COLLECTION_DRIVER = "LOCAL_COLLECTION_DRIVER" ;
	public static String FTP_COLLECTION_DRIVER="FTP_COLLECTION_DRIVER";
	public static String SFTP_COLLECTION_DRIVER="SFTP_COLLECTION_DRIVER";

	public static String DATA_CONSOLIDATION_SERVICE = "DATA_CONSOLIDATION_SERVICE" ;
	
	public static final String ENGINE_START_SERVER_DEFAULT_FILE = "startServer.sh";
	public static final String TELNET_INVALID_CREDENTIALS = "TELNET_INVALID_CREDENTIALS" ;
	public static final String TELNET_PROTOCOL_MISMATCH = "PROTOCOL_MISMATCH" ;
	public static final String TELNET_CONNECTION_FAILED = "Not able to get Connection" ;
	
	public static final String NATFLOW_COLLECTION_SERVICE="NATFLOW_COLLECTION_SERVICE";
	public static final String NATFLOWBINARY_COLLECTION_SERVICE="NATFLOWBINARY_COLLECTION_SERVICE";
	public static final String IPLOG_PARSING_SERVICE="IPLOG_PARSING_SERVICE";
	public static final String AGGREGATION_SERVICE="AGGREGATION_SERVICE";
	public static final String GTPPRIME_COLLECTION_SERVICE="GTPPRIME_COLLECTION_SERVICE";
	public static final String SYSLOG_COLLECTION_SERVICE="SYSLOG_COLLECTION_SERVICE";
	public static final String MQTT_COLLECTION_SERVICE="MQTT_COLLECTION_SERVICE";
	public static final String COAP_COLLECTION_SERVICE="COAP_COLLECTION_SERVICE";
	public static final String HTTP2_COLLECTION_SERVICE="HTTP2_COLLECTION_SERVICE";
	public static final String CORRELATION_SERVICE="CORRELATION_SERVICE";
	public static final String RADIUS_COLLECTION_SERVICE="RADIUS_COLLECTION_SERVICE";
	public static String RAP_PARSING_PLUGIN = "RAP_PARSING_PLUGIN";
	public static String TAP_PARSING_PLUGIN = "TAP_PARSING_PLUGIN";
	public static String NRTRDE_PARSING_PLUGIN = "NRTRDE_PARSING_PLUGIN";
	public static String FIXED_LENGTH_BINARY_PARSING_PLUGIN = "FIXED_LENGTH_BINARY_PARSING_PLUGIN";
	public static String PDF_PARSING_PLUGIN = "PDF_PARSING_PLUGIN";
	public static final String DIAMETER_COLLECTION_SERVICE="DIAMETER_COLLECTION_SERVICE";
	

}
